### ISSUE TITLE
Does the Asnq task only need to enter questions and labels?

### ISSUE THREAD

**Issue by lduml** [alexa/wqa_tanda#1]
I don't know if I didn't understand the ideas of the paper.  After reading the paper,  I think the Asnq task needs to input questions,  candidates answer sentences, as well as the label. But in the code when handling Asnq task only see the input questions and label, did not see the candidate answer sentences. Can you explain it to me? Thank you very much.

`
class AsnqProcessor(DataProcessor):
...
def _create_examples(self, lines, set_type):
...
examples.append(
                InputExample(guid=guid, text_a=text_a, text_b=None, label=label))
 `

**Comment by parhamouni** [comment]
text_a is the question, text_b is the answer, and label determines whether it is a true question answer pair or not.

**Comment by vuthuyfo** [comment]
parhamouni@ has answered the question correctly, so I closed the issue.

**Comment by lduml** [comment]
thanks

**Comment by lduml** [comment]
Why the text_b in the code is always None? As I mentioned above.

**Comment by vuthuyfo** [comment]
thank you lduml@; yes, that line was incorrect, i have fixed it.
