### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by mouxingyang** [alexa/wqa_tanda#11]
Hi~~   It is a really nice job. However, I cannot find the source code. Could you please release your code or send me a copy of that?

Best regard!

**Comment by sid7954** [comment]
Hi! 
We have provided a [diff file](https://github.com/alexa/wqa_tanda/blob/master/tanda-sequential-finetuning-with-asnq.diff) that you can apply to the huggingface transformers repository following the directions outlined [here](https://github.com/alexa/wqa_tanda/blob/master/tanda-sequential-finetuning-with-asnq.diff).
