### ISSUE TITLE
Can not download asnq dataset

### ISSUE THREAD

**Issue by Wenorm** [alexa/wqa_tanda#12]
when i download asnq by:
wget https://wqa-public.s3.amazonaws.com/tanda-aaai-2020/data/asnq.tar3
then get a error as below:
azonaws.com (wqa-public.s3.amazonaws.com)|52.217.77.164|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-02-25 17:44:51 ERROR 403: Forbidden.

**Comment by chengran-yang** [comment]
I met the same issue. Have you already solved it?

**Comment by Wenorm** [comment]
> I met the same issue. Have you already solved it?

It has been solved, just open a vip member of [Thunder](https://www.xunlei.com/).

**Comment by autumn-city** [comment]
> 

Thx! It really works

**Comment by chengran-yang** [comment]
> > I met the same issue. Have you already solved it?
> 
> It has been solved, just open a vip member of [Thunder](https://www.xunlei.com/).

Thx! It really works!

**Comment by sid7954** [comment]
We have updated the links to the ASNQ data and model checkpoints on the repository.
