### ISSUE TITLE
Task not found: asnq

### ISSUE THREAD

**Issue by ryanpram** [alexa/wqa_tanda#7]
Hi, i got error "ValueError: Task not found: asnq" when i run run_glue.py. I already do this step:

- git clone https://github.com/huggingface/transformers.git
- cd transformers
- git checkout f3386 -b tanda-sequential-finetuning
- git apply tanda-sequential-finetuning-with-asnq.diff

When i apply tanda-sequential-finetuning-with-asnq.diff, 3 file is change => run_glue.py, __init__.py, glue.py.

Any steps that i missed?

**Comment by ryanpram** [comment]
Sorry i did wrongly import the transformers

**Comment by kasidkhansbp** [comment]
Hi @ryanpram 

1. I am also trying to the above steps but at 4th step (git apply tanda-sequential-finetuning-with-asnq.diff) it throws an error as "'tanda-sequential-finetuning-with-asnq.diff': No such file or directory".

2. Also, after 3rd step (git checkout f3386 -b tanda-sequential-finetuning), it did say "Switched to a new branch 'tanda-sequential-finetuning'" but I do not see the "tanda-sequential-finetuning-with-asnq.diff" in the folder. 

Any idea, what could I have done wrong?
